(global-set-key (kbd "C-:") 'avy-goto-char)
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-x b") 'helm-buffers-list)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "M-<up>") 'windmove-up)
(global-set-key (kbd "M-<down>") 'windmove-down)
(global-set-key (kbd "M-<left>") 'windmove-left)
(global-set-key (kbd "M-<right>") 'windmove-right)
(global-set-key (kbd "C-<up>") 'beginning-of-defun)
(global-set-key (kbd "C-<down>") 'end-of-defun)
(global-set-key (kbd "C-c i") 'indent-buffer)
(global-set-key (kbd "C-x 3") 'new-window-right)


(provide 'init_keys)
